### ISSUE TITLE
Calories: Does not let you enter the number “2.” This gets converted to “200.”

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#10]
> Calories: Does not let you enter the number “2.” This gets converted to “200.”

I am unable to reproduce; entering 2 seems to work without problem. Any number above 200 is converted to 200. Is this functionality undesired? Does the whole team prefer that we allow any numeric input and then show an error dialog when the whole form is submitted?

**Comment by Jacquelyn-Rudis** [comment]
Also could not reproduce the 2 changing to a 200. Please keep parameters and auto-conversions as-is. Thanks!
