### ISSUE TITLE
Cannot use a comma when entering steps

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#11]
> Cannot use a comma- does not alert child what is wrong when they use commas it just gets stuck and doesn’t let them move forward (saw this when entering steps). Specific alert needed

For various reasons, commas are filtered out of the input. Is it not clear that the child should just enter the numbers when pressing a comma doesn't do anything? If not, how can we make this more clear? Or, is something more meant by "it just gets stuck and doesn't let them move forward"? There should be no problem pressing, for example, '1' followed by a comma followed by three other digits.

**Comment by Jacquelyn-Rudis** [comment]
When a child entered "1,000" the comma remained and pressing the advance button did not advance.  Are you saying that the comma should disappear and that the child should be able to move forward?

**Comment by TAGraves** [comment]
Yes, the expected behavior is that pressing the comma button does _not_ add a comma; the button press is just ignored, and no comma should appear. Are you able to successfully add a comma?

**Comment by Jacquelyn-Rudis** [comment]
Yes I watched a child trying to add a comma on Monday, I don't think it was
the regular data input screen. It was further along in the level. Not sure
what level I will try to reproduce today on tablet.

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/

**Comment by TAGraves** [comment]
Ah, I see. I'll consider this a duplicate of #28, then. Closing this, since this issue will be fixed once that one is implemented.
