### ISSUE TITLE
Various issues with the timer

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#12]
> Getting stuck if time is not entered with minutes listed- no indication that this is why though so the kids don’t know which field to change to move forward. Specific alert needed.
> In update- Cannot delete/back space. To fix an entry error, need to start typing from the beginning of entering a number, and if it is less than 10 have to type a “0” first. 
> Also can’t type over an entered number. Not intuitive to start typing the whole entry again

Please describe in close detail the exact functionality desired with the timer. I.e.,
What should happen when backspace is pressed and the cursor is at the first position, the second position, the last position, etc.?
What should happen when the cursor is in a middle position and a number is typed? (e.g. if '23:45' is entered and the cursor is between the '2' and the '3' and '7' is pressed, what should the expected result be? '27:45'? '27:34'?)
And so on.

**Comment by Jacquelyn-Rudis** [comment]
The cursor should always be at the end on the right, as if they were typing on a computer or a smartphone. If they need to make an adjustment they should press the backspace button and numbers should delete from right to left. They shouldn’t be able to place the cursor in a middle position.

**Comment by TAGraves** [comment]
@Jacquelyn-Rudis, could I get a little more clarification on what you're expecting? Suppose what's entered in the timer is '12:34' and backspace is pressed. You say numbers should delete from right to left. Does that mean the result should be '12:30', or does it mean the result should be '01:23'?

**Comment by Jacquelyn-Rudis** [comment]
01:23 thank you!

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/

**Comment by TAGraves** [comment]
Okay, this has been implemented in commit cc96c0994eefd4ca863a2292801ace3c06159481 - that'll be available tomorrow morning, so try it out then and let me know if it's up to par.

**Comment by Jacquelyn-Rudis** [comment]
The timer looks great, apologies for the late confirmation!
