### ISSUE TITLE
Number of attempts should be tracked

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#14]
> Zi’s spreadsheet asking for back end data fields included tracking the number of attempts that a child made on a question before getting it correct. Is this built in?

I was never informed that this was a requirement. It will be built in. Please provide a list of anything that needs to be tracked aside from the answers students provide and have accepted by the app.

**Comment by scottdebney** [comment]
Sorry Tommy, this is my mistake. Thanks.  They tracked how many times a student answered the questions wrong (tries) I forgot this requirement and may have missed it in any communication.

**Comment by Jacquelyn-Rudis** [comment]
Hi- To break down what we would like tracked:
-Number of times a child answers a question incorrectly and is allowed to move forward (regular level), as well as which questions they are getting wrong and which part of the multi-step questions (if possible)

-Number of times a child answers a question incorrectly and has to go back and try again to get it right (bonus questions in each level)- which questions they are getting wrong, which part of the multi-step questions (if possible), how many attempts it takes to get it right

-Number of times a child enters data incorrectly on data entry screen, both entering a number outside of the parameters as well as entering time/MVPA incorrectly

**Comment by TAGraves** [comment]
@Visavant Here's how I'm handling this in https://github.com/YMCACOLUMBUS/activescience/commit/bc8f8fa1b0b66e8fedc2407b820837de9a6ae1d9 - let me know if you'd rather it be done another way.

Every time one of the things Jacquelyn wanted tracked occurs, I write to SQLite with details on the incorrect answer (level #, question #, what the student entered - activityType is 3). I then set a 5 second timer preventing any further writes, to prevent tracking when a student is incessantly answering incorrectly out of stubbornness, mischief, or glitch (so, max 12 transactions per minute). On the app side, we never need to see this data again, so I'd prefer if you don't send it to me when I call for the transact data. My idea of how this would work is when the C# parser receives the whole payload of data, it calculates # of times each question was answered incorrectly (based on the entries sent up for each question) and stores that in the database alongside the specific data on the incorrect answers. Then the app clears those entries from the SQLite db. I guess the difficulty of implementation for you is that once the master tablet clears the entries, how will the child tablets know that the entries have been cleared? As I understand it, what will instead happen is the child tablets will think they have entries the master tablet doesn't have and so they will send those entries to the master again instead of deleting them.
