### ISSUE TITLE
Penalty for dying in Asteroids game

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#16]
> Arrow takes a little while to reappear
> 
> Do you lose points if the asteroid hits the arrow? Kids view that as “dying” but I don’t see points deducted

The intention is that the penalty for dying is losing some time before the ship reappears, since you only have a minute to play. Is it preferable that the ship instantly reappears and some points are deducted? We can make changes here, but let's have a discussion about what we want.

**Comment by scottdebney** [comment]
I really don't think we should change the game here.  If we slow down play, it might become annoying.  I agree if you die, you lose points because you lose time.

**Comment by Jacquelyn-Rudis** [comment]
Makes sense, leaving it at is sounds good!

**Comment by scottdebney** [comment]
One thing that "may" be helpful, is have a visual count down in the game?  So they can see time ticking away?

**Comment by TAGraves** [comment]
See issue #17 for that, Scott - I plan on implementing that. Going to close this issue since there seems to be agreement on no change.
