### ISSUE TITLE
Add a countdown time for the game

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#17]
> Timer for the game - add countdown?

**Comment by Jacquelyn-Rudis** [comment]
Updated version - no countdown

**Comment by TAGraves** [comment]
@scottdebney Could you mock up a design with a countdown included for both BuddyJump and Asteroids?

**Comment by scottdebney** [comment]
Here's the asteroids, also increased the font size on the points as well.  
![asteroids-counter](https://cloud.githubusercontent.com/assets/5481333/15191915/d15f4754-1784-11e6-9190-d716afaeed0e.png)

**Comment by scottdebney** [comment]
BuddyJump Counter.  
![counter-2](https://cloud.githubusercontent.com/assets/5481333/15192936/87ac1902-1789-11e6-88d5-ee17a3918565.png)
