### ISSUE TITLE
Data table answer indicators

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#20]
> -Need arrows to indicate which answer was chosen/is right on graph

As it stands right now, which hypothesis was chosen is stated in the text to the left of the chart, and which answer is correct is easily readable by understanding the chart. What is the intention behind adding the arrows?

**Comment by scottdebney** [comment]
Maybe, instead of and arrow we could highlight the table fields they chose?  I think the arrow is to be intuitive so they see immediately what they chose.

**Comment by Jacquelyn-Rudis** [comment]
Yes an arrow or highlight would be helpful. Visual learning tool. Thanks!

**Comment by TAGraves** [comment]
A highlight sounds good to me - @Jacquelyn-Rudis , how should it work? Should we only highlight which cell is their hypothesis? Should we highlight both their hypothesis and the correct answer? If so, what do we do in the case where their hypothesis is the correct answer?

**Comment by Jacquelyn-Rudis** [comment]
Hi- I think that adding an arrow to the left of the table, next to the day, that indicates their hypothesis will be sufficient. The goal is for them to be able to refer to a line when considering "was your hypothesis correct?" Highlighting the whole cell with the number may indicate that the highlighted cell is the correct answer.

**Comment by Jacquelyn-Rudis** [comment]
Level 3 (Grade 3-4) - No indication of which part of the table was their hypothesis. Arrow needed. Also in table after playing the game.

**Comment by TAGraves** [comment]
Jacquelyn, there should be an arrow in the most recent update - try closing and reopening the app while connected to wifi to see if you can pull down the newest.

**Comment by Jacquelyn-Rudis** [comment]
Yes I can see the arrow once on Wifi. Thank you! Both the bluetooth and
wifi versions said Version 15?

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/

**Comment by TAGraves** [comment]
Version 15 refers to the version of the APK, but most of the changes that I make to the interface are considered curriculum changes and so are independent of the APK. Curriculum changes happen automatically when your device connects to wi-fi - once we make our v1.0 release to production, curriculum changes will also be distributed over bluetooth, but that currently is disabled for testing purposes. So, to clarify, there can be multiple curricula versions available to you when your APK is on version 15. (The advantage of this is that if we want to add a new world, for instance, a teacher will not have to go through every tablet and press 'Install Update' - once one tablet is connected to wi-fi it will download the new world and distribute it to the other tablets without the teacher having to do anything).

This also should explain why you were seeing the wrong bonus question for level 3 - that should also be fixed now that you have the newest curriculum.

**Comment by Jacquelyn-Rudis** [comment]
Perfect, that makes a lot of sense. Thank you!

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/
