### ISSUE TITLE
Implement bonus question process of elimination

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#21]
> This question is too difficult for most children observed. To make it more manageable and less frustrating could we do the following?
> In the first drop down menu, alert the child if they got the answer correct or not. Once they get the answer right, “unlock” the second drop down.
> In the second drop down menu, have the remaining two options available, alert if they got the second part incorrect.
> In the third drop down menu, have them choose the final option
> Remove “your answer” from the dropdown menu

**Comment by Jacquelyn-Rudis** [comment]
In all questions with multiple drop down menus, could we have this "process of elimination" factor built in? Also, could some (not all) of the drop down menu/ordering questions be changed to "drag and drop" (similar to the assessments)? This would better mirror the pre and post assessment.

**Comment by TAGraves** [comment]
Yes to both, though this may take some time to develop.

Questions to be adjusted:
Level 3 Bonus Question
Level 4 Bonus Question
Level 7 Bonus Question
Level 8 Bonus Question (this seems like a good candidate for drag and drop)
Level 9 Bonus Question
Level 10 Bonus Question
Level 11 Bonus Question
Level 12 Bonus Question (again, good candidate for drag and drop)

**Comment by TAGraves** [comment]
This has been implemented and will be available tomorrow.
