### ISSUE TITLE
Change to curriculum, level 3 bonus question

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#22]
> Besides the assessment, the scientific methods was not mentioned prior to this point 
>     It should probably be introduced somehow before it is incorporated in this level

How should it be introduced? As far as I am aware there was no introduction of the method in the curriculum provided to us.

**Comment by Jacquelyn-Rudis** [comment]
Kevin is looking back through curriculum and will let me know if an update to the curriculum needs to be made. Will update
