### ISSUE TITLE
If the steps and rest of data don’t correspond with each other, it does not tell you why you cannot advance

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#23]
> If the steps and rest of data don’t correspond with each other, it does not tell you why you cannot advance (i.e. can enter 10 steps but 3 miles)

Please describe in more detail what is being asked for here. I am unable to reproduce being prevented from advancing when entering 10 steps but 3 miles - the form appears to accept those as valid numbers. If what is desired is more validation of the numbers entered, **please give specific requirements** for the additional validation.

**Comment by Jacquelyn-Rudis** [comment]
I believe this is in reference to the data entry field. The ranges for the limits of data entry that Kevin provided should be sufficient. It may result in some "bad data" if a child enters both 10 steps and 3 miles (which logically don't correspond) but the upper and lower limits should be sufficient as is.

**Comment by TAGraves** [comment]
Closing this as it sounds like the existing data validation is sufficient and the issue quoted was probably related to another input bug.
