### ISSUE TITLE
Mission 1 level 7 graph displays incorrectly

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#25]
> Words for the questions on mission 1 level 7, bar chart screen are still not fixed, they are covered by the bars

**Comment by Jacquelyn-Rudis** [comment]
Words still covered by bar graphs. "Bonus Question" graphic is also small on this screen in upper left. In upper right, "go" button covers "Level 7". Also, if change is made to "hypothesis" screen to say "levels" instead of "days," the bar graph labels should reflect that change also.
