### ISSUE TITLE
Specify that you can lose before 60 seconds in Buddy Jump

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#26]
> Specify that you only have one attempt

**Comment by TAGraves** [comment]
@scottdebney Could you update the SVG with the instructions to note this? Ideally it might also say something like "After 5 seconds, falling too far will cause you to lose!" (you are invincible for 5 seconds)

**Comment by scottdebney** [comment]
Here you go!  
[how-to-play-buddy-update.svg.zip](https://github.com/YMCACOLUMBUS/activescience-issues/files/260022/how-to-play-buddy-update.svg.zip)
