### ISSUE TITLE
Validate input data on all levels

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#28]
> It is looking for miles but there is no error trapping process like there is in the initial data entry section at the start of the level that prevents you from adding any more than 5 miles

**Comment by Jacquelyn-Rudis** [comment]
Still an issue, noticed on Level 8 entering Friend's miles

**Comment by TAGraves** [comment]
Just FYI, for future reference, if an issue is still open that means we are aware it is still a problem - I close issues once I have made a fix for them.

**Comment by TAGraves** [comment]
This was added in commit a319ccffedb7e03f7a4a353ff10f432029454cd8 and will be available for testing tomorrow.
