### ISSUE TITLE
Level 9 data table graphic is unclear

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#30]
> The data table graphic in this screen is a little confusing, I don’t think they will understand what it is. 

Do we want to use a different graphic for this level? @scottdebney ?

**Comment by scottdebney** [comment]
Let me review.

**Comment by scottdebney** [comment]
Right on, use this one if you would!  Thanks!
[data-table-row.svg.zip](https://github.com/YMCACOLUMBUS/activescience-issues/files/248911/data-table-row.svg.zip)

**Comment by TAGraves** [comment]
Jacquelyn, does this work as an alternative?
![data-table-row](https://cloud.githubusercontent.com/assets/2263711/15021756/8de2f2d4-11f6-11e6-9f9c-615192b2bf58.png)

**Comment by scottdebney** [comment]
she approved that graphic

On Wed, May 4, 2016 at 12:49 PM, Tommy notifications@github.com wrote:

> Jacquelyn, does this work as an alternative?
> [image: data-table-row]
> https://cloud.githubusercontent.com/assets/2263711/15021756/8de2f2d4-11f6-11e6-9f9c-615192b2bf58.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/YMCACOLUMBUS/activescience-issues/issues/30#issuecomment-216928631

## 

_Scott Debney_
_Executive Director of Technology and Web Services_
YMCA OF CENTRAL OHIO
40 West Long Street, Columbus OH 43215
*P *614 224 1137 x 130  *C *614 747 2120
*E *sdebney@ymcacolumbus.org  *W *ymcacolumbus.org
*FB *facebook.com/ymcacolumbusohio  *T *twitter.com/ymcacolumbus

http://twitter.com/ymcacolumbus

**Comment by TAGraves** [comment]
Fixed in 2b26803fcade14f667a41d055a6a5966191355bb
