### ISSUE TITLE
Don't advance until answer is correct.

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#33]
> Make sure that if the answer is incorrect, that the student cannot advance until the next screen until they answer correctly - on all levels.

Is the suggestion that even the "Was your hypothesis correct" questions should prevent students from advancing until they are answered correctly? If not, what is the suggestion? If so, this is contrary to how Kevin said he wanted those questions to work, so I will need a unified answer from the team on what is wanted.

**Comment by Jacquelyn-Rudis** [comment]
If the incorrect answer is entered , have a popup alert (as is currently in app) with the correct answer but let the child proceed without changing their original answer.

**Comment by TAGraves** [comment]
Sorry, I'm still confused on this matter. Isn't that how it currently works?

**Comment by Jacquelyn-Rudis** [comment]
Yes I believe so. Some of the students during field testing were using the
older version of the app prototype on the two tablets that originally
worked (before the font issue was figured out) so the feedback may have
come from observing those students. The latest update has this feature and
it looks great. Thank you!

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/

**Comment by TAGraves** [comment]
Great, thanks. Closing this.
