### ISSUE TITLE
Pre-Test Question 1, Grade 1

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#35]
"Drag and drop" instruction should be bigger/in bold so students know what to do

**Comment by TAGraves** [comment]
Is this big enough?
![image](https://cloud.githubusercontent.com/assets/2263711/15052906/fa775f20-12cd-11e6-95ef-ab07e56fc0b3.png)

**Comment by Jacquelyn-Rudis** [comment]
Yes looks good! Could Drag and drop be in bold or slightly larger font?

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/

**Comment by TAGraves** [comment]
Made 'Drag and Drop' bigger and updated this in commit afc466c7d9df0ab4a943edbd24cd8c35862dd265 - you should see it in tomorrow morning's update.
