### ISSUE TITLE
Log out button

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#36]
Can we add a "return to current level" as an option in case the child hits log out by mistake

**Comment by TAGraves** [comment]
Do you prefer this solution to adding a popup box "Are you sure you want to log out?" when they try to log out in the middle of a level?

**Comment by Jacquelyn-Rudis** [comment]
I like the "are you sure you want to log out" pop up box idea better, thank
you!

Jacquelyn Rudis
Director, Operations and Development
Active Science
Department of Health Sciences
Merrimack College
North Andover, Massachusetts

Office: 978-837-5734
Email: rudisj@merrimack.edu

Website http://activescienceforkids.org/# | Facebook
https://www.facebook.com/activescienceforkids/

**Comment by TAGraves** [comment]
Implemented in commit 6253f31a41ccd45afab4f39b4cdb8e94c65366c9 - should be available tomorrow!
