### ISSUE TITLE
Clarify question on first grade level 6

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#37]
> We wanted to illustrate the beach ball rolling, baseball rolling, and soccer ball rolling, then ask the kids to relate the observation back to what they are experimenting. The choice should be soccer ball rolling since we are trying to compare the soccer ball and football in the experiment. Is there a better way to illustrate the the pictures are rolling? The goal of this question is to relate an experiment with an observation.  

Thoughts, @scottdebney?

**Comment by scottdebney** [comment]
So we'll have use some short video clips... I will get those to you within
the hour.

On Thu, May 5, 2016 at 2:09 PM, Tommy notifications@github.com wrote:

> We wanted to illustrate the beach ball rolling, baseball rolling, and
> soccer ball rolling, then ask the kids to relate the observation back to
> what they are experimenting. The choice should be soccer ball rolling since
> we are trying to compare the soccer ball and football in the experiment. Is
> there a better way to illustrate the the pictures are rolling? The goal of
> this question is to relate an experiment with an observation.
> 
> Thoughts, @scottdebney https://github.com/scottdebney?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/YMCACOLUMBUS/activescience-issues/issues/37

## 

_Scott Debney_
_Executive Director of Technology and Web Services_
YMCA OF CENTRAL OHIO
40 West Long Street, Columbus OH 43215
*P *614 224 1137 x 130  *C *614 747 2120
*E *sdebney@ymcacolumbus.org  *W *ymcacolumbus.org
*FB *facebook.com/ymcacolumbusohio  *T *twitter.com/ymcacolumbus

http://twitter.com/ymcacolumbus

**Comment by scottdebney** [comment]
Here you go, try these.  Still put them in the box and have 2-4vw border around the choices and put these inside?  

![animated_funball-red-yellow-beach-ball](https://cloud.githubusercontent.com/assets/5481333/15053090/e079a6fe-12ce-11e6-86b9-22156788f083.GIF)
![baseball-animated-gif](https://cloud.githubusercontent.com/assets/5481333/15053089/e0790686-12ce-11e6-9531-b270d2d7937a.gif)
![soccer-ball-rotating-animation](https://cloud.githubusercontent.com/assets/5481333/15053088/e078380a-12ce-11e6-88bf-0b0e4557e07b.gif)

**Comment by TAGraves** [comment]
Updated in commit bb13147d1052e6160d57b1802e6da024b1d3b377
