### ISSUE TITLE
Game start feature

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#38]
The start feature is not intuitive (they often click in the middle where the asteroids are moving, then the orange button because it looks like fire, then finally the “fire” button). Can they click the middle of the screen where the game is to start?

**Comment by TAGraves** [comment]
Sure, I will make it so tapping on the game or on any of the buttons will start the game.

**Comment by TAGraves** [comment]
Added in commit 21c4ea4145f74922b1491fb79a4cb9aac4b14c5a - check for this tomorrow!
