### ISSUE TITLE
Arrow in upper right corner of screen on game

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#39]
Arrow in upper right corner of screen on game during beginning of game, does not move, asteroids pass over it

**Comment by TAGraves** [comment]
That arrow shouldn't be appearing; it will be removed.

**Comment by TAGraves** [comment]
Fixed in commit 3f5835d226ed0665d1ea0ce33eab6c4acfaf854c - look for this in tomorrow's update!
