### ISSUE TITLE
Go button and "bonus question" graphic on Bonus Question screen

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#44]
Level 4 The "Go" button in the bottom right is covering the "Level 4" label and is very small.

Also GO button is small on Level 8 Bonus screen. Have to tap multiple times to move forward.

"Bonus Question" graphic is also small on Level 8

Same issue with both buttons on Level 9

**Comment by TAGraves** [comment]
I have a list of all the screens where this issue occurs; it'll be fixed soon.

**Comment by TAGraves** [comment]
Fixed in commit 61be161a60082145853f21c0e4e010cc1ea06ef1, available tomorrow.
