### ISSUE TITLE
Level 8 wording update - data analysis screen

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#50]
On the data analysis graph screen, under the bar graphs it says “You hypothesized that friend 2 would travel the shortest.  Can we add “distance” after the word shortest so it reads: “You hypothesized that friend 2 would travel the shortest distance”

**Comment by TAGraves** [comment]
Added in commit b5b168c115ece72df5b78286bfd7d4ad26770afe, will be available tomorrow.
