### ISSUE TITLE
Level 9 data analysis wording

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#52]
When looking at the Data Analysis screen, it says “ You hypothesized that you traveled farther last time." Can we change this to read “You hypothesized that you traveled farther last time than you did today”

**Comment by TAGraves** [comment]
Fixed in https://github.com/YMCACOLUMBUS/activescience/commit/448408f9dac8caddfc6d17abd39143c6a3abb3ce
