### ISSUE TITLE
level 11 Hypothesis

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#53]
Hypothesis: The text indicates “What Level (level) do you think you traveled the farthest so far?  Remove the (level) in parenthesis.

When I enter a level, it should be a limit on the range (1-11) but when I entered 18, it allowed me to move forward. When I did this, a pop up should have said something like “Please enter a level within the range”

**Comment by TAGraves** [comment]
Completed the first part of this in commit fec70ddcad5e6b148f15e0fb1ca4f9ed675c18f0.

The second part will be completed along with issue #28
