### ISSUE TITLE
Level 11 game 

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#54]
Game: There should be a limit on the  number of points that you can hypothesize. I added in a large number like 4,000,000 and it allowed this to work. When I went to look at the graph, it was trying to display my hypothesized number and the actual, which was difficult to read on the graph. I am not sure what is a reasonable point maximum value but we should decide and add this in for the games where we hypothesize a value.

**Comment by TAGraves** [comment]
I added a limit of 40000 points for BuddyJump and 15000 points for Asteroids, which are about twice what I think the highest possible score is. (Commit a319ccffedb7e03f7a4a353ff10f432029454cd8) - available tomorrow.
