### ISSUE TITLE
Switch Bonus questions for Levels 3 and 4

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#55]
Move Level 3 Bonus question to Level 4.

Use Part 1 of Level 4 Bonus question for the Level 3 Bonus Question:
Bonus Question for Level 3 should now be: “Today you collected (Data is the answer but other options are same as question in level 4) to see what day you took the most steps."

**Comment by TAGraves** [comment]
This was implemented in commit 4ed32cc2936f5f9d050d6300fbc22d7dadea5d05, available tomorrow.

**Comment by Jacquelyn-Rudis** [comment]
I'm on Version 15 (on Bluetooth) and Level 3 Bonus was Steps of Scientific Method. Level 4 Bonus is the same question (steps of scientific method)

Disregard- It brought me through Level 4 twice bc I did not complete the game
