### ISSUE TITLE
Grade 1 + 2 Pre-test Question 1 and font setting change

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#58]
"Drag and Drop" instructions are cut off at the bottom for Question 1. Tablet font size was "large." I changed the font setting to "normal" and got the navy blue Active Science (underlined) screen with "Learn More" at the bottom. Clicked "Learn More" and directed to old Active Science website (right part of page cut off). Back button does not work to return to app. Going to home page on tablet and clicking on new Active Science icon brings me to the same website page. Cleared Data in settings on tablet and could then log back in to the app. Logged in with font size "normal" - Drag and drop instructions still cut off.

**Comment by TAGraves** [comment]
Thanks - there are a few different issues here. The drag and drop issue was just because I forgot to send one update to the production server, so that will be fixed tomorrow. 

Looping @Visavant on the Learn More button since that probably doesn't need to be there right now.
