### ISSUE TITLE
Grade 1 + 2 Pre-Test Question 4

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#60]
Graph not labeled on left.

**Comment by TAGraves** [comment]
The grade 1 pre-test question 4 is "Which surface has the most friction" and doesn't contain a graph. Did you mean question 6 (Favorite foods by type)?

**Comment by Jacquelyn-Rudis** [comment]
Apologies, I meant Question 3 (didn't realize Buddy was covering the #3 on the top to indicate that was the question displayed)

**Comment by TAGraves** [comment]
Fixed with b64245c998c8b65f0b570b3335101374a6228a80
