### ISSUE TITLE
TTS - No audio / Older Kindle Model

### ISSUE THREAD

**Issue by Visavant** [YMCACOLUMBUS/activescience-issues#66]
ID : 466ce4b59709a82
Model : KFASWI LMY470
OS: full_ariel
ITMTTS <-> IVONA

Unthrown exception, no audio from TTS. Older sites using KFASWI, Merrimack insists on sale of licenses instead of device with new iteration. KFFOWI utilizes IVONA, ITMTTS engine not being invoked by the application context.

Awaiting acquisition from SDEBNEY on or after 5/16

**Comment by scottdebney** [comment]
This appeared to be a volume button was all the way down.
