### ISSUE TITLE
"Drag and Drop" instruction- Grade 3+4

### ISSUE THREAD

**Issue by Jacquelyn-Rudis** [YMCACOLUMBUS/activescience-issues#67]
Assessment Question #1- "Drag and drop" needs to stand out more- bold and larger (like Grade 1+2 instructions)?

**Comment by TAGraves** [comment]
Fixed in https://github.com/YMCACOLUMBUS/activescience/commit/214f91951d0b686c0ea7c59a62a39a8dc58495e3
