### ISSUE TITLE
Lock World Button After 1 Level Completed.  

### ISSUE THREAD

**Issue by scottdebney** [YMCACOLUMBUS/activescience-issues#69]
So after a student completes a level please lock or disable the home world button for 120 minutes.

**Comment by scottdebney** [comment]
Once the world is locked and a student clicks or press the world, alert "You've already completed your level for today!"

**Comment by TAGraves** [comment]
An initial implementation of this is available in https://github.com/YMCACOLUMBUS/activescience/commit/4c6edd1cf321a3df95d0ae28fae7ead0ebce1d6c - only issue with it is that a student can log out, immediately log back in, then complete another level. That'll be fixed tomorrow and then this will be pushed to production on Thursday.

**Comment by scottdebney** [comment]
Awesome!   Thanks!

**Comment by TAGraves** [comment]
Added in https://github.com/YMCACOLUMBUS/activescience/commit/c8ad59105bbbe44b7471e552e4c4a37673027aec
