### ISSUE TITLE
Add Steps next to Points on Rankings Page

### ISSUE THREAD

**Issue by scottdebney** [YMCACOLUMBUS/activescience-issues#71]
So on the attached page, add total steps and not just points.  
![steps](https://cloud.githubusercontent.com/assets/5481333/15339243/7803435a-1c51-11e6-93df-1f407443f386.png)

**Comment by TAGraves** [comment]
Added in https://github.com/YMCACOLUMBUS/activescience/commit/a8f40323b21a370cd7c8ca9143cf07f0b95ae2a1
