### ISSUE TITLE
New Leaderboard Stats

### ISSUE THREAD

**Issue by scottdebney** [YMCACOLUMBUS/activescience-issues#72]
An easy was for Active Science to have "challenges" from the start.  There will be 3 automatic leader boards that would reset each, Month, week, day based on the time stamps for activities logged.   

**Each Month** (Jan, Feb, Mar, April, May, June, July, August, Sep, Oct, Nov, Dec)

**Each Current Week** (Monday 12:00:00a - Sunday 11:59:59p) Eastern Time

**Each Day** 12:00:00-11:59:59 Eastern Time

[assets.zip](https://github.com/YMCACOLUMBUS/activescience-issues/files/270570/assets.zip)

**Comment by TAGraves** [comment]
How is current day supposed to work when there are multiple tablets being used?

**Comment by scottdebney** [comment]
So, it should sync right, maybe it could be previous day?  Would that be easier?

**Comment by scottdebney** [comment]
Or just start with Month and Week?  Day can come last if it's a bigger issue.

**Comment by TAGraves** [comment]
Previous day still doesn't make much sense when you consider that not all sites do it every day. Actually, for that matter, weekly doesn't make sense for sites that do it once a week.

**Comment by scottdebney** [comment]
Yeah, that's a good point Tommy. The first thought they had was monthly (the other measurements were just thrown in there).... so let's just start with month.  Can you put the label on the month?

**Comment by TAGraves** [comment]
Added the monthly challenge in https://github.com/YMCACOLUMBUS/activescience/commit/7fda49b50b921bb590b4f4fff3a246fd0e9d5d90

In order to implement challenges, I need to rework the way I calculate points from the beginning-of-mission assessments. I disabled points for those assessments until the rework is completed.

**Comment by TAGraves** [comment]
Implemented (albeit a bit sloppily) in https://github.com/YMCACOLUMBUS/activescience/commit/aa483a8d3d01515c57d8d40a0b3626af79f1625a.
