### ISSUE TITLE
Pick a level - if press and hold too long, cannot move forward

### ISSUE THREAD

**Issue by TAGraves** [YMCACOLUMBUS/activescience-issues#8]
> “Pick a Level” Screen
> Functionality - if press and hold too long, cannot move forward

I am unable to reproduce this problem; could someone please provide more detailed information about the problem?

**Comment by Jacquelyn-Rudis** [comment]
Observed a child have this issue but also was not able to reproduce

**Comment by TAGraves** [comment]
Let me know if you figure out a way to replicate it. It may have just been a bug with the older version.
